import ListPosts from "@/components/list-posts";
import Summary from "@/components/summary";
import Head from "next/head";
import { PostData, getSortedPostsData } from "../../lib/posts";

export default function Home({ allPostsData }: { allPostsData: PostData[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Summary />
        <ListPosts data={allPostsData} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};
